#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/889e97f4-1ef6-48a0-907d-bdd66d28fe6b 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool botonCloud;
  bool detenerCloud;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// Pines botones
const uint8_t detener = D5;
const uint8_t abrir_cerrar = D6;

// Pines salidas
const uint8_t motor1 = D1;
const uint8_t motor2 = D2;

// Variables de estado
bool lastEstadoLimite = HIGH;
bool lastEstadoBoton = HIGH;

bool dirSiguiente = true;  // true -> D1, false -> D2

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  pinMode(detener, INPUT_PULLUP);
  pinMode(abrir_cerrar, INPUT_PULLUP);

  pinMode(motor1, OUTPUT);
  pinMode(motor2, OUTPUT);

  digitalWrite(motor1, LOW);
  digitalWrite(motor2, LOW);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  bool estadoLimite  = digitalRead(detener);
  bool estadoBoton = digitalRead(abrir_cerrar);

 // Si se pulsa alguno de los interruptores de limite, el motor se para
 if (lastEstadoLimite == HIGH && estadoLimite == LOW) {
        digitalWrite(motor1, LOW);
        digitalWrite(motor2, LOW);
    }

    // Si se pulsa el boton y el motor esta parado, se empieza a girar en la direccion contraria a la que estaba girando antes
 if (lastEstadoBoton == HIGH && estadoBoton == LOW) {

        if (digitalRead(motor1) == LOW && digitalRead(motor2) == LOW) {
            if (dirSiguiente) {
                digitalWrite(motor1, HIGH);
                digitalWrite(motor2, LOW);
            } else {
                digitalWrite(motor1, LOW);
                digitalWrite(motor2, HIGH);
            }

            // Alternar para la próxima vez
            dirSiguiente = !dirSiguiente;
        }
    }

    lastEstadoLimite  = estadoLimite;
    lastEstadoBoton = estadoBoton;

    delay(20); // antirrebote simple
  
  
}

/*
  Since BotonCloud is READ_WRITE variable, onBotonCloudChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBotonCloudChange()  {
  // Add your code here to act upon BotonCloud change
  if (digitalRead(motor1) == LOW && digitalRead(motor2) == LOW) {
            if (dirSiguiente) {
                digitalWrite(motor1, HIGH);
                digitalWrite(motor2, LOW);
            } else {
                digitalWrite(motor1, LOW);
                digitalWrite(motor2, HIGH);
            }

            // Alternar para la próxima vez
            dirSiguiente = !dirSiguiente;
        }
}

/*
  Since DetenerCloud is READ_WRITE variable, onDetenerCloudChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDetenerCloudChange()  {
  // Add your code here to act upon DetenerCloud change
  digitalWrite(motor1, LOW);
  digitalWrite(motor2, LOW);
}