// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "40853a5f-71a4-4ee5-b4ab-dae942527efa";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBotonCloudChange();
void onDetenerCloudChange();

bool botonCloud;
bool detenerCloud;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(botonCloud, READWRITE, ON_CHANGE, onBotonCloudChange);
  ArduinoCloud.addProperty(detenerCloud, READWRITE, ON_CHANGE, onDetenerCloudChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
